# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 437bf7b8548605082c3caa82aa85ba4816ed61e635c63419a1cc0b9d6185a2fb3627eb0d2808ed7fc10211bac1f7786c7241522935bc40dbf23c96bece921bee

test:
  secret_key_base: cbf4a9fd9e7a3dc0b8bd9faa4c003988a91d8a0838b5018f93a9c3c0ce75943f0c2419a836d931345cd3427ba353002c9d179a298b8cac1a764f1fa0264ae3dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
